---
title: "correlation_analysis_3.Rmd"
author: "Serim Jang (serimj)"
date: "7/9/2019"
output: html_document
  html_document:
    toc: true
    toc_float: true
---

```{r}
# Finding distribution of smoking sessions by study duration
ggplot(data=subset(smoking_session, session_label == "smoking_session"),
       aes(x=day_label)) + geom_bar(stat="count", aes(fill=high_status2)) +
  scale_x_continuous(breaks=0:33) +
  labs(title = "Smoking Sessions Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,20)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of high surveys (1-10) by study duration
ggplot(data=subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=day_label)) + geom_bar(stat="count", aes(fill=high_status2)) +
  scale_x_continuous(breaks=0:33) +
  labs(title = "High Surveys Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,40)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of high levels by study duration
ggplot(data=uniq_integ,
       aes(x=day_label, fill=high_status)) +
  geom_bar(stat="count") +
  scale_x_continuous(breaks=0:33) +
  labs(title = "High Levels Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,175)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of high levels by study duration
ggplot(data=uniq_integ,
       aes(x=day_label)) +
  geom_bar(stat="count", aes(fill=high_status2)) +
  scale_x_continuous(breaks=0:33) +
  labs(title = "High Levels Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,175)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of craving levels by study duration
ggplot(data=uniq_integ,
       aes(x=day_label, fill=craving_status)) + geom_bar(stat="count") +
  scale_x_continuous(breaks=0:33) +
  labs(title = "High Levels Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,175)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of craving levels by study duration
ggplot(data=uniq_integ,
       aes(x=day_label)) + geom_bar(stat="count", aes(fill=craving_status2)) +
  scale_x_continuous(breaks=0:33) +
  labs(title = "High Levels Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,175)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of craving surveys (1-10) by study duration
ggplot(data=subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=day_label)) + geom_bar(stat="count") +
  scale_x_continuous(breaks=0:33) +
  labs(title = "Craving Surveys Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,100)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
# Finding distribution of craving surveys (1-10) by study duration
ggplot(data=subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=day_label)) + geom_bar(stat="count", aes(fill=craving_status2)) +
  scale_x_continuous(breaks=0:33) +
  labs(title = "Craving Surveys Reported Throughout Study Duration",
       x ="Study Duration", y = "Count") +
  coord_cartesian(xlim=c(1,33), ylim=c(0,100)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            high_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H")

# Finding distribution of high surveys (1-10) by hour
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=time)) + geom_bar(stat="count") +
  labs(title = "High Surveys Reported Throughout the Day",
       x = "Time of Day", y = "Count") +
  scale_x_datetime(date_breaks = "1 hour",
                   date_labels = "%H:%M", timezone = "America/New_York",
                   expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            high_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H")

# Finding distribution of high surveys (1-10) by hour
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=time)) + geom_bar(stat="count", aes(fill=high_status2)) +
  labs(title = "High Surveys Reported Throughout the Day",
       x = "Time of Day", y = "Count") +
  scale_x_datetime(date_breaks = "1 hour",
                   date_labels = "%H:%M", timezone = "America/New_York",
                   expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            high_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H:%M:%S")

# Finding distribution of high level by hour
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
              aes(x=time, y=how_high)) +
  geom_point(na.rm = TRUE, size = 1.5, alpha = 0.3) +
  labs(title = "High Level Reported Throughout the Day",
       x = "Time of Day", y = "How High") +
  scale_x_datetime(date_breaks = "1 hour",
                   labels = time_format("%H:%M", tz = "America/New_York")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0)) +
  scale_y_continuous(limits=c(0,10), breaks=seq(0,10, by = 1))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            craving_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H")

# Finding distribution of craving surveys (1-10) by hour
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=time)) + geom_bar(stat="count") +
  labs(title = "Craving Surveys Reported Throughout the Day",
       x = "Time of Day", y = "Count") +
  scale_x_datetime(date_breaks = "1 hour",
                   date_labels = "%H:%M", timezone = "America/New_York",
                   expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            craving_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H")

# Finding distribution of craving surveys (1-10) by hour
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=time)) + geom_bar(stat="count", aes(fill=craving_status2)) +
  labs(title = "Craving Surveys Reported Throughout the Day",
       x = "Time of Day", y = "Count") +
  scale_x_datetime(date_breaks = "1 hour",
                   date_labels = "%H:%M", timezone = "America/New_York",
                   expand = c(0,0)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0))
```

```{r}
time_conv = strftime(subset(uniq_integ,
                            craving_status %in% c("L","M","H"))$timestamp,
                     format="%H:%M:%S")
time = as.POSIXct(time_conv, format="%H:%M:%S")

# Finding distribution of craving level by hour
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H"))
       , aes(x=time, y=craving)) +
  geom_point(na.rm = TRUE, size = 1.5, alpha = 0.3) +
  labs(title = "Craving Level Reported Throughout the Day",
       x = "Time of Day", y = "Craving") +
  scale_x_datetime(date_breaks = "1 hour",
                   labels = time_format("%H:%M", tz = "America/New_York")) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.0, hjust = 1.0)) +
  scale_y_continuous(limits=c(0,10), breaks=seq(0,10, by = 1))
```

```{r}
# Finding distribution of high surveys (1-10) by day of week
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=week)) + geom_bar(stat="count") +
  labs(title = "High Surveys Reported Throughout the Week",
       x = "Day of Week", y = "Count")
```

```{r}
# Finding distribution of high surveys (1-10) by day of week
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=week)) + geom_bar(stat="count", aes(fill=high_status2)) +
  labs(title = "High Surveys Reported Throughout the Week",
       x = "Day of Week", y = "Count")
```

```{r}
# Finding distribution of craving surveys (1-10) by day of week
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=week)) + geom_bar(stat="count") +
  labs(title = "Craving Surveys Reported Throughout the Week",
       x = "Day of Week", y = "Count")
```

```{r}
# Finding distribution of craving surveys (1-10) by day of week
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=week)) + geom_bar(stat="count", aes(fill=craving_status2)) +
  labs(title = "Craving Surveys Reported Throughout the Week",
       x = "Day of Week", y = "Count")
```

```{r}
# Finding distribution of high level by hour
ggplot(subset(uniq_integ, high_status %in% c("L","M","H")),
       aes(x=week, y=how_high)) +
  geom_point(na.rm = TRUE, size = 1.5, alpha = 0.05) +
  labs(title = "High Level Reported Throughout the Week",
       x = "Day of Week", y = "How High")
```

```{r}
# Finding distribution of high level by hour
ggplot(subset(uniq_integ, craving_status %in% c("L","M","H")),
       aes(x=week, y=craving)) +
  geom_point(na.rm = TRUE, size = 1.5, alpha = 0.01) +
  labs(title = "Craving Level Reported Throughout the Week",
       x = "Day of Week", y = "How High")
```

## Finding relationship between cognitive scores & `act_freq`

### Stroop

```{r}
# Finding relationship between S_perc_cor and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=S_perc_cor, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Stroop Percent Correct") +
  stat_compare_means(label.x = 0.8, label.y = 0.84) +
  scale_y_continuous(limits=c(0.8,1))
```

```{r}
# Finding relationship between S_avg_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=S_avg_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Stroop Average Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 520) +
  scale_y_continuous(limits=c(500,1000))

round(mean(subset(uniq_integ, act_freq == "heavy")$S_avg_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$S_avg_response, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between S_sd_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=S_sd_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Stroop Response Time Std Dev (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 430) +
  scale_y_continuous(limits=c(0,500))
```

```{r}
# Finding relationship between S_max_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=S_max_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Stroop Maximum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 4250) +
  scale_y_continuous(limits=c(500,5000))

round(mean(subset(uniq_integ, act_freq == "heavy")$S_max_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$S_max_response, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between S_min_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=S_min_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Stroop Minimum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 430) +
  scale_y_continuous(limits=c(300,700))

round(mean(subset(uniq_integ, act_freq == "heavy")$S_min_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$S_min_response, na.rm=TRUE), 3)
```

### DSST

```{r}
# Finding relationship between D_perc_cor and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=D_perc_cor, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "DSST Percent Correct") +
  stat_compare_means(label.x = 0.8, label.y = 0.8) +
  scale_y_continuous(limits=c(0.8,1))
```

```{r}
# Finding relationship between D_avg_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=D_avg_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "DSST Average Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 1030) +
  scale_y_continuous(limits=c(1000,2000))
```

```{r}
# Finding relationship between D_sd_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=D_sd_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "DSST Response Time Std Dev (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 100) +
  scale_y_continuous(limits=c(0,2000))
```

```{r}
# Finding relationship between D_max_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=D_max_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "DSST Maximum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 9100) +
  scale_y_continuous(limits=c(0,10000))
```

```{r}
# Finding relationship between D_min_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=D_min_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "DSST Minimum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 1470) +
  scale_y_continuous(limits=c(500,1500))
```

### Flowers

```{r}
# Finding relationship between F_perc_cor and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=F_perc_cor, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Flowers Percent Correct") +
  stat_compare_means(label.x = 0.8, label.y = 0.55) +
  scale_y_continuous(limits=c(0.5,1))

round(mean(subset(uniq_integ, act_freq == "heavy")$F_perc_cor, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$F_perc_cor, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between F_avg_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=F_avg_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Flowers Average Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 500) +
  scale_y_continuous(limits=c(200,600))

round(mean(subset(uniq_integ, act_freq == "heavy")$F_avg_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$F_avg_response, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between F_sd_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=F_sd_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Flowers Response Time Std Dev (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 530) +
  scale_y_continuous(limits=c(0,600))

round(mean(subset(uniq_integ, act_freq == "heavy")$F_sd_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$F_sd_response, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between F_max_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=F_max_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Flowers Maximum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 100) +
  scale_y_continuous(limits=c(0,1000))

round(mean(subset(uniq_integ, act_freq == "heavy")$F_max_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$F_max_response, na.rm=TRUE), 3)
```

```{r}
# Finding relationship between F_min_response and act_freq
ggplot(data=uniq_integ,
       aes(x=act_freq, y=F_min_response, fill=act_freq)) +
  geom_boxplot() + labs(x ="Smoking Frequency", y = "Flowers Minimum Response Time (ms)") +
  stat_compare_means(label.x = 0.8, label.y = 100) +
  scale_y_continuous(limits=c(50,500))

round(mean(subset(uniq_integ, act_freq == "heavy")$F_min_response, na.rm=TRUE), 3)
round(mean(subset(uniq_integ, act_freq == "regular")$F_min_response, na.rm=TRUE), 3)
```